const response = {
	items: [
		{
			model: '320i',
			modelVersion: 'SPORT GP NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '320i',
			modelVersion: 'M SPORT NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'M SPORT NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '320i',
			modelVersion: 'M SPORT NAC 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '320i',
			modelVersion: 'M SPORT 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP 2.0 16V AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB 184CV AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB 184CV AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB 184CV AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '320i',
			modelVersion: 'SPORT GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '320i',
			modelVersion: 'M SPORT 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '320i',
			modelVersion: 'GP 2.0 16V TB AT8',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M3',
			modelVersion: 'SEDAN COMPETITION 3.0 BI-TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M3',
			modelVersion: 'SEDAN COMPETITION TRACK 3.0 BI-TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M3',
			modelVersion: 'SEDAN COMPETITION TRACK 3.0 BI-TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M3',
			modelVersion: 'SEDAN COMPETITION 3.0 BI-TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M5',
			modelVersion: 'COMPETITION 4.4 V8 BI-TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X5',
			modelVersion: 'M50d 4X4 3.0 TB 400CV',
			numberOfDoors: 4,
			fuelType: 'Dies.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X5',
			modelVersion: 'M50d 4X4 3.0 TB 400CV',
			numberOfDoors: 4,
			fuelType: 'Dies.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '330i',
			modelVersion: 'M SPORT 2.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '330i',
			modelVersion: 'M SPORT NAC 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '330i',
			modelVersion: 'M SPORT NAC 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '330i',
			modelVersion: 'M SPORT NAC 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '330i',
			modelVersion: 'M SPORT 2.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'Z4 ROADSTER',
			modelVersion: 'sDrive30i M SPORT 2.0 TB',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'Z4 ROADSTER',
			modelVersion: 'M40i 3.0',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive20i X LINE 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive20i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive20i X LINE 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive20i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive20i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30i X LINE 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30i X LINE 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'M40i 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'M40i 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive30i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive30i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X3',
			modelVersion: 'M COMPETITION 4X4 3.0 BI-TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'M COMPETITION 4X4 3.0 BI-TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. xDrive30i X LINE 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30e HIBRIDO 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30e HIBRIDO 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30e X LINE HIBRIDO 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'xDrive30e X LINE HIBRIDO 4X4 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. M40i 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. M40i 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X3',
			modelVersion: 'NAC. M40i 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X6',
			modelVersion: 'xDrive40i M SPORT 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X6',
			modelVersion: 'xDrive40i M SPORT 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X6',
			modelVersion: 'xDrive40i M SPORT 4X4 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X6',
			modelVersion: 'M 4X4 4.4 V8 600CV',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X6',
			modelVersion: 'M 4X4 4.4 V8 600CV',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X6',
			modelVersion: 'M 4X4 4.4 V8 600CV',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '118i',
			modelVersion: 'SPORT GP 1.5 TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '118i',
			modelVersion: 'SPORT GP 1.5 TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X1',
			modelVersion: 'xDrive25i SPORT NAC 2.0 16V ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X1',
			modelVersion: 'xDrive25i SPORT NAC 2.0 16V ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X1',
			modelVersion: 'xDrive25i SPORT NAC 2.0 16V ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X5',
			modelVersion: 'xDrive45e M SPORT HIBRIDO 4X4 3.0',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X5',
			modelVersion: 'xDrive45e M SPORT HIBRIDO 4X4 3.0',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X5',
			modelVersion: 'xDrive45e M SPORT HIBRIDO 4X4 3.0',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X5',
			modelVersion: 'M50i 4X4 4.4 V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X5',
			modelVersion: 'M50i 4X4 4.4 V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X5',
			modelVersion: 'M COMPETITION 4X4 4.4 V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X5',
			modelVersion: 'M COMPETITION 4X4 4.4 V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i GP NAC 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i X-LINE 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i GP NAC 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i X-LINE 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i GP NAC 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i X-LINE 2.0 16V 192CV ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i M SPORT 25 ANOS 2.0 16V',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i M SPORT 25 ANOS 2.0 16V',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X1',
			modelVersion: 'sDrive20i M SPORT 25 ANOS 2.0 16V',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M135i',
			modelVersion: 'xDRIVE 2.0 16V TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M235i',
			modelVersion: 'xDRIVE GRAN COUPE 2.0 16V TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M235i',
			modelVersion: 'xDRIVE GRAN COUPE 2.0 16V TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M235i',
			modelVersion: 'DARK EDITION 2.0 16V TB AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'i3',
			modelVersion: '120Ah BEV',
			numberOfDoors: 4,
			fuelType: 'Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'i3',
			modelVersion: '120Ah BEV CONNECTED',
			numberOfDoors: 4,
			fuelType: 'Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'i3',
			modelVersion: '120Ah REX FULL 0.6',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'i3',
			modelVersion: 'BEV 42KWH FULL',
			numberOfDoors: 4,
			fuelType: 'Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive40i M40i 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive40i M40i 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X4',
			modelVersion: 'M COMPETITION 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive40i M40i 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X4',
			modelVersion: 'M COMPETITION 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X4',
			modelVersion: 'M COMPETITION 4X4 3.0 TB 24V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT NAC 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT NAC 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X4',
			modelVersion: 'xDrive30i M SPORT NAC 4X4 2.0 TB 16V',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M4 COUPE',
			modelVersion: '3.0 V6 24V BI-TB MT6',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M4 COUPE',
			modelVersion: 'COMPETITION 3.0 V6 24V BI-TB MT6',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M2',
			modelVersion: 'COMPETITION 3.0 24V',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M2',
			modelVersion: 'COMPETITION ED.ESPECIAL 3.0 BI-TB MT',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M2',
			modelVersion: 'CS 3.0 BI-TB ATM',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '430i',
			modelVersion: 'CABRIO M SPORT 2.0 TB',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '430i',
			modelVersion: 'CABRIO M SPORT 2.0 TB',
			numberOfDoors: 2,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive18i GP 1.5 TB AT',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive18i GP 1.5 TB AT',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i GP 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i GP 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive18i GP 1.5 TB AT',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i GP 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i M SPORT X 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i M SPORT X 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i M SPORT X 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i M SPORT X(Rodas Aro 20) 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X2',
			modelVersion: 'sDrive20i M SPORT X(Rodas Aro 20) 2.0 16V TB ACTIVEFLEX',
			numberOfDoors: 4,
			fuelType: 'Eta./Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Completo',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT DARK EDITION 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT DARK EDITION 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Completo',
		},
		{
			model: '530e',
			modelVersion: 'M SPORT DARK EDITION 2.0 16V BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M760LI',
			modelVersion: 'xDRIVE 6.6 V12',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M760LI',
			modelVersion: 'xDRIVE 6.6 V12',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'X7',
			modelVersion: 'M50i 4X4 4.4 BI-TB V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'X7',
			modelVersion: 'M50i 4X4 4.4 BI-TB V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Completo',
		},
		{
			model: 'X7',
			modelVersion: 'M50i 4X4 4.4 BI-TB V8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '745Le',
			modelVersion: 'M SPORT 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: '745Le',
			modelVersion: 'M SPORT 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '745Le',
			modelVersion: 'M SPORT DARK EDITION 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: '745Le',
			modelVersion: 'M SPORT DARK EDITION 3.0 TB',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '218I',
			modelVersion: 'GRAN COUPE SPORT GP 1.5 12V AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: '218I',
			modelVersion: 'GRAN COUPE SPORT GP 1.5 12V AT',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: '330E',
			modelVersion: 'M SPORT 2.0 TB HYBRID',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'Basico',
		},
		{
			model: '330E',
			modelVersion: 'M SPORT 2.0 TB HYBRID',
			numberOfDoors: 4,
			fuelType: 'Gas./Eletr.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M340I',
			modelVersion: 'xDRIVE 3.0 TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M340I',
			modelVersion: 'xDRIVE 3.0 TB AT8',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M8',
			modelVersion: 'GRAND COUPE COMPETITION FIRST EDITION 4.4 V8 BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M8',
			modelVersion: 'GRAND COUPE COMPETITION FIRST EDITION 4.4 V8 BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
		{
			model: 'M8',
			modelVersion: 'GRAND COUPE COMPETITION 4.4 V8 BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'Basico',
		},
		{
			model: 'M8',
			modelVersion: 'GRAND COUPE COMPETITION 4.4 V8 BI-TB',
			numberOfDoors: 4,
			fuelType: 'Gas.',
			accessoryPackage: 'BlindadoN3',
		},
	],
	cursors: {},
};

module.exports = response;